In [79]:
import matplotlib.pyplot as plt
import numpy as np
from math import *
from numpy.linalg import inv 

In [80]:
lambda x, y, z, t : 2*x + 5*y + 4*z + t - 20
lambda x, y, z, t : x + 3*y + 2*z + t - 11
lambda x, y, z, t : 2*x + 10*y + 9*z + 7*t - 40
lambda x, y, z, t : 3*x + 8*y + 9*z + 2*t - 37

<function __main__.<lambda>(x, y, z, t)>

In [81]:
def Gauss(A, B):
    n = len(B)
    X = np.zeros(n, dtype= float)
    #forward elimination part
    for k in range(n - 1):
        for i in range(k + 1, n):
            factor = A[i,k] / A[k,k]
            for j in range(k, n):
                A[i,j] = A[i,j] -  factor * A[k,j]
            B[i] = B[i] - factor * B[k]                  
    #backward substitution
    X[n - 1] = B[n - 1] / A[n - 1, n - 1]
    for i in range(n-2, -1, -1):
        sum_ = 0
        for j in range(i+1, n):
            sum_ += A[i,j] * X[j]
        X[i] = (B[i] - sum_) / A[i,i]
        
    return X

In [82]:
A = np.array([[2, 5 ,4 , 1], [1, 3, 2, 1], [2, 10, 9, 7], [3, 8, 9, 2]], dtype=float)
B = np.array([[20], [11], [40], [37]], dtype=float)
print(f"Augmented matrix of the system of linear equations:\n{A}")
print(f"B matrix of the system of linear equations:\n {B}")
print(F"Checking the roots: {np.linalg.solve(A,B)}")
print(f"Solution of system: \n{Gauss(A,B)}")

#print(F"Checking the roots: {np.linalg.solve(A,B)}")
print(inv(A).dot(B))

Augmented matrix of the system of linear equations:
[[ 2.  5.  4.  1.]
 [ 1.  3.  2.  1.]
 [ 2. 10.  9.  7.]
 [ 3.  8.  9.  2.]]
B matrix of the system of linear equations:
 [[20.]
 [11.]
 [40.]
 [37.]]
Checking the roots: [[ 1.00000000e+00]
 [ 2.00000000e+00]
 [ 2.00000000e+00]
 [-1.60189322e-15]]
Solution of system: 
[ 1.  2.  2. -0.]
[[1.]
 [2.]
 [2.]
 [0.]]


In [83]:
X = Gauss(A,B)
np.matmul(A, X)

array([20.,  1., 10.,  0.])

In [84]:
len(A)
len(B)

4